### ISSUE TITLE
Insertions at end of reads

### ISSUE THREAD

**Issue by rnpandya** [amplab/snap#1]
From Ilya Chorny ichorny@gmail.com

The aligner places insertion at the end of reads. For example the CIGAR string looks as follows. 6I1=4I89=. You should probably soft-clip the insertions at the ends. Not even clear what an insertion at the ends means.

**Comment by bolosky** [comment]
This is fixed (and has been for several versions).  The code no longer generates cigar strings that start (or end) with I or D, after clipping, and in the debug build it validates that this is the case for every generated cigar.
