### ISSUE TITLE
`soft_exit_no_print(1)` returns 1 instead of 0 when calling help

### ISSUE THREAD

**Issue by mmterpstra** [amplab/snap#109]
Your default help messages return 1 as error code and the default is 0 for a good exit. Here is an example.

```
./snap-1.0beta.18/snap-aligner index --help
Welcome to SNAP version 1.0beta.18.
... 
$ echo $?
1
$ cat --help
...
$ echo $?
0
 ```

Possible solutions (pick whatever catches your fancy)
- rewrite usage to take an exit code (`usage_with_exit(0)`)
- exit locally after calling `usage()`
- wrap usage into two other subroutines one exits correctly with error code 0 and another exits with error code 1.
- Think of a nice one!

One of the afflicting  `soft_exit_no_print(1)` statements is present at :

https://github.com/amplab/snap/blob/f11c1314558e73ed802fb3dfa0e7c96f4ccbfdbb/SNAPLib/GenomeIndex.cpp#L94

**Comment by bolosky** [comment]
Fixed in 1.0.  (BTW, this was only ever for the index command.)
