### ISSUE TITLE
Error - No overlapping contigs found during variant calling pre processing

### ISSUE THREAD

**Issue by ramcn** [amplab/snap#115]
Hello,

I ran the SNAP tool on SRR622461 dataset and trying to use the generated SAM file for variant calling using GATK. But seeing an "no overlapping contigs found error" during RealignerTargetCreator GATK command. 

The attached script sbatch-script has the detailed pipeline command and sbatch-log has the error seen during the RealignerTargetCreator GATK command. Please let me know if you any clue about how to fix this error. 

[sbatch-log.txt](https://github.com/amplab/snap/files/2036273/sbatch-log.txt)
[sbatch-script.txt](https://github.com/amplab/snap/files/2036274/sbatch-script.txt)

**Comment by ramcn** [comment]
PS: the workflow steps in script works fine when I use aligners like bwa mem and bowtie.

**Comment by bolosky** [comment]
That error means that the contig names that SNAP is generating don’t correspond to the ones that GATK expects.

SNAP gets its contig names from its index, so they’re determined at index build time.  There are a few options to deal with thing like spaces in the contig names in the FASTA reference used during index build that you might need to use.  (For example, the -b or -bSpace flags.)

I’d suggest looking at the header in the SAM file generated by SNAP to see what they look like (look for the @SQ lines) and compare them to the ones in the GRCH 38 reference, and you’ll probably see what’s happening.

If that doesn’t make sense to you, send me some examples of @SQ lines and I’ll figure out what’s up.

--Bill

**Comment by ramcn** [comment]
OK. I am attaching the snap sam file header.
[snap-header.txt](https://github.com/amplab/snap/files/2040580/snap-header.txt)

Please let me know if you can figure something out. I am using human_g1k_v37.fasta reference file.

Thank you,
Ram

**Comment by bolosky** [comment]
Your contig names are things like this:

1_dna:chromosome_chromosome:GRCh37:1:1:249250621:1

When they should just be “1”.   To fix this, you’ll need to rebuild SNAP’s index and add in a couple of options:
-bSpace -B_

(the second one is dash B underscore).  That tells SNAP that when it sees a space or an underscore that it’s at the end of the contig name and it should just use what it’s seen.

Once you’ve rebuilt the index, rerun SNAP and the error should go away.

--Bill

**Comment by ramcn** [comment]
Hi Bill

Reindexing with these options worked and the error is gone.

Thank you,
Ram
