### ISSUE TITLE
snap speedup above 32 threads

### ISSUE THREAD

**Issue by ramcn** [amplab/snap#116]
Hello,

I am doing performance study of SNAP on skylake processor (stampede2 system) which has 48*2=96 hardware threads per node. The initial experiments show that beyond 32 threads there isn't much speedup.

Is this a known limitation? If there is any particular code optimization which I can try out to gain speedup beyond 32 threads, kindly provide some insights.

Thank you,
Ram

**Comment by bolosky** [comment]
The scaling limit on SNAP typically is the system memory bandwidth.  Every lookup in the hash table is at least one cache miss all the way to memory, and sometimes a few more.  Likewise, every reference into the reference genome to check a candidate alignment is also a cache miss to memory (unless there are several candidates nearby).

There’s really not all that much you can do about it.  One possibility that might help a little is to try the -hp option, which will use huge pages for the index.  This might make index load slow (on Windows, it’s so awful that you won’t want to use it, on Linux somewhat less but still painful).  This will result in fewer translation lookaside buffer misses (if you don’t know what this is, don’t worry, it’s something internal to the processor that takes both time and memory bandwidth).  That might help some, and might not, depending on what’s really the problem.

There’s also some possibility that you’re IO limited and you can’t read/write the data fast enough.  You can tell the difference between the two by looking at the processor load.  If it’s memory bandwidth, the cores will be running at (or close to) 100%, while if it’s IO then you’ll see much lower CPU load.

--Bill

**Comment by ramcn** [comment]
Thanks for the suggestions. I will profile the application and get more  information about memory IO and CPU utilization and try to figure out what is going on.
