### ISSUE TITLE
sort option -so expected functionality

### ISSUE THREAD

**Issue by ramcn** [amplab/snap#117]
Hello,

I am assuming the functionality of -so option is equivalent to samtools sort and trying to use -so option to generate output bam sorted by coordinate as below. But when I use it to create index using samtools I get a failure as alignment is not sorted.

**- snap-aligner paired snap-index-dir SRR1586015_1.fastq SRR1586015_2.fastq -t 32  -so -o -bam snap-1x.bam**
**- samtools index snap-1x.bam**
[bam_index_core] the alignment is not sorted (SRR1586015.3826889): 56024334 > 56024332 in 18-th chr

Please let me know if this is expected behavior or a bug.

Thank you,
Ram

**Comment by bolosky** [comment]
This was fixed a while ago, I no longer remember in which version, but certainly it's OK in 2.0.
