### ISSUE TITLE
sort issue

### ISSUE THREAD

**Issue by jpofmars** [amplab/snap#120]
Hello,

I get sort error with tools like GATK or samtools.
It seems that the sort was done on the 8th column and GATK wants the sort was done on the 4th column
I'm using SNAP version 1.0beta.23.
 
Here an example of error : 

` ##### ERROR M00402:105:000000000-C9YJM:1:2113:13559:16965	81	3	3146516	23	2M1I9M1D1M1D91M	3	3146515	-105	TACAATAATGTTTATTTTTCTAACATATTTTTAAAAATAAACATTATTGAATTGAATAGAAGGTCCTTACTCTTTTCATCAGGAAGTAAGTCAGCTTGCAGTAT	HFFHHHGGG3FHFHAFHEHHHHGGHHFHHHFHHHHHHGHHHFHFHHFHHHHHHHHHHGHHGFCFHGGDGHFCFHFFHHHFFHGGGGGGGGCGFBFFFFFBBBBA	LB:Z:XXX	PG:Z:SNAP	RG:Z:XXX	PL:Z:ILLUMINA	NM:i:6`
`##### ERROR M00402:105:000000000-C9YJM:1:2113:13559:16965	161	3	3146515	23	12M1D1M1D91M	3	3146516	105	TTCAATAATGTTTATTTTTCTAACATATTTTTAAAAATAAACATTATTGTATTGAATAGAAGGTCCTTACTCTTTTCATCAGGAAGTAAGTCAGCTTGCAGTAT	BAAAAFBDFFDFGGGFGGGEGGHGFHHHHGFHHCGHCFHHHHHFH5DGF5BGGF55EGHFHFFHFHHHB3DGHGHFGHEHHHHHCHBFHHHF5BGHHHHEFBGH	LB:Z:XXX	PG:Z:SNAP	RG:Z:XXX	PL:Z:ILLUMINA	NM:i:8	
`

thank you

**Comment by bolosky** [comment]
It’s definitely not trying to sort by pnext (column 8) instead of pos (column 4).  Did you look in the output of SNAP to be sure that they’re really out of order, instead of just relying on GATK?  If so, then it’s probably a bug and I’ll follow up with you to see if I can repro it.

**Comment by bolosky** [comment]
The newly release 1.0 version has sort (and duplicate) marking that produces output that goes through GATK (at least HaplotypeCaller) fine.  I'm closing this issue.  If you still see a problem, please reopen it or create a new issue.
