### ISSUE TITLE
Has any version can index fasta file more large than 4.2G？

### ISSUE THREAD

**Issue by Winjor** [amplab/snap#122]
Hi，I see the same question in google group，but not solved yet. Are there any way or any version of SNAP can do that?  
By the way, I see the version is updated to 1.0beta.24 in master from update log and actively in some branches, any latest version will release？

**Comment by bolosky** [comment]
Any version of SNAP should be able to index a genome of any practical size.  If it’s bigger than 232 bases, or really even close to that, you’ll need to say -locationSize 5 when you build the index.  That’s even true for the human genome if you use a small seed size (for reasons too complicated to explain here).  If you try to index something too big, you should get an error message telling you to increase -locationSize.  If you have something truly huge (like 240 bases) and the memory to hold such an index, maybe you’ll need -locationSize 6.

We’re working on a set of major updates to SNAP.  In particular, we’ve added affine gap scoring with which SNAP calls indels with about the same precision and recall as bwa-mem, but much, much faster.  I’m not sure of the schedule for actually releasing it, but it shouldn’t be too long.

--Bill
