### ISSUE TITLE
Occur Segmentation fault (core dumped) problem

### ISSUE THREAD

**Issue by sjlgg** [amplab/snap#123]
i run the software like following:

`snap-aligner index CP009072.1.fasta ./CP009072_index
Welcome to SNAP version 1.0beta.24.

Hash table slack 0.300000
Loading FASTA file 'CP009072.1.fasta' into memory...
FASTA file contained a character that's not a valid base (or N): 'Y', full line 'TGCGGCCCCGGAAAATGAAAACATGGCCGGACATGGGATCGTCTTTCAGCGCCGTYTGTACTTTCGCAGC'; 
converting to 'N'.  This may happen again, but there will be no more warnings.
0s
Saving genome...0s
Computing bias table.
Computed bias table in 0s
Allocating memory for hash tables...0s
Building hash tables.
53749(1%) seeds occur more than once, total of 132985(2%) genome locations are not unique, 764(0%) bad seeds, 0 both complements used 500 no string
Hash table build took 0s
Building overflow table.
Overflow table build and hash table save took 0s
Saving overflow table...0s
Index build and save took 0s (5131767 bases/s)`

after build index:

`snap-aligner single CP009072_index/ SRR2061818.fastq -o alignment_CP009072_result.sam
Welcome to SNAP version 1.0beta.24.

Loading index from directory... 0s.  5131767 bases, seed size 20
Aligning.
Segmentation fault (core dumped)`

i dont know why the error happen. could someone help me?
[CP009072.1.fasta download from here](https://www.ebi.ac.uk/ena/data/view/CP009072&display=fasta&download=fasta&filename=CP009072.fasta)
[SRR2061818.fastq download from here](ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR206/008/SRR2061818/SRR2061818.fastq.gz)
SRR2061818,fastq link is here: ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR206/008/SRR2061818/SRR2061818.fastq.gz

**Comment by bolosky** [comment]
The FASTQ link isn’t a link, could you please resend it?

--Bill

**Comment by sjlgg** [comment]
> The FASTQ link isn’t a link, could you please resend it?
> […](#)
> --Bill From: sjlgg <notifications@github.com> Sent: Tuesday, October 22, 2019 4:30 AM To: amplab/snap <snap@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [amplab/snap] Occur Segmentation fault (core dumped) problem (#123) i run the software like following: `snap-aligner index CP009072.1.fasta ./CP009072_index Welcome to SNAP version 1.0beta.24. Hash table slack 0.300000 Loading FASTA file 'CP009072.1.fasta' into memory... FASTA file contained a character that's not a valid base (or N): 'Y', full line 'TGCGGCCCCGGAAAATGAAAACATGGCCGGACATGGGATCGTCTTTCAGCGCCGTYTGTACTTTCGCAGC'; converting to 'N'. This may happen again, but there will be no more warnings. 0s Saving genome...0s Computing bias table. Computed bias table in 0s Allocating memory for hash tables...0s Building hash tables. 53749(1%) seeds occur more than once, total of 132985(2%) genome locations are not unique, 764(0%) bad seeds, 0 both complements used 500 no string Hash table build took 0s Building overflow table. Overflow table build and hash table save took 0s Saving overflow table...0s Index build and save took 0s (5131767 bases/s)` after build index: `snap-aligner single CP009072_index/ SRR2061818.fastq -o alignment_CP009072_result.sam Welcome to SNAP version 1.0beta.24. Loading index from directory... 0s. 5131767 bases, seed size 20 Aligning. Segmentation fault (core dumped)` i dont know why the error happen. could someone help me? CP009072.1.fasta download from here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ebi.ac.uk%2Fena%2Fdata%2Fview%2FCP009072%26display%3Dfasta%26download%3Dfasta%26filename%3DCP009072.fasta&data=02%7C01%7Cbolosky%40microsoft.com%7C1380e8bb50964d32ca7c08d756e32b1d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637073405986340899&sdata=Q8fXrXXYhk6ILxyOHJ3zgpRA73BbMzQZdpGonZhAKX0%3D&reserved=0> SRR2061818.fastq download from here — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famplab%2Fsnap%2Fissues%2F123%3Femail_source%3Dnotifications%26email_token%3DAAHPTWJHPNZQGWJ6ZDNFF3LQP3P3LA5CNFSM4JDOJ2N2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HTPBJJQ&data=02%7C01%7Cbolosky%40microsoft.com%7C1380e8bb50964d32ca7c08d756e32b1d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637073405986350903&sdata=cNFV3MMc37sX2unUg5ZwDAD6RgkX%2B7oPtQ4aXD5eV2c%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHPTWKGIP3W5SJIX6WVPSDQP3P3LANCNFSM4JDOJ2NQ&data=02%7C01%7Cbolosky%40microsoft.com%7C1380e8bb50964d32ca7c08d756e32b1d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637073405986350903&sdata=a5XwGv3lAFDx5TuOSmPjcu6eFSo8tfRKeyFqi7IqDCw%3D&reserved=0>.

ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR206/008/SRR2061818/SRR2061818.fastq.gz

**Comment by sjlgg** [comment]
> The FASTQ link isn’t a link, could you please resend it?
> […](#)
> --Bill From: sjlgg <notifications@github.com> Sent: Tuesday, October 22, 2019 4:30 AM To: amplab/snap <snap@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [amplab/snap] Occur Segmentation fault (core dumped) problem (#123) i run the software like following: `snap-aligner index CP009072.1.fasta ./CP009072_index Welcome to SNAP version 1.0beta.24. Hash table slack 0.300000 Loading FASTA file 'CP009072.1.fasta' into memory... FASTA file contained a character that's not a valid base (or N): 'Y', full line 'TGCGGCCCCGGAAAATGAAAACATGGCCGGACATGGGATCGTCTTTCAGCGCCGTYTGTACTTTCGCAGC'; converting to 'N'. This may happen again, but there will be no more warnings. 0s Saving genome...0s Computing bias table. Computed bias table in 0s Allocating memory for hash tables...0s Building hash tables. 53749(1%) seeds occur more than once, total of 132985(2%) genome locations are not unique, 764(0%) bad seeds, 0 both complements used 500 no string Hash table build took 0s Building overflow table. Overflow table build and hash table save took 0s Saving overflow table...0s Index build and save took 0s (5131767 bases/s)` after build index: `snap-aligner single CP009072_index/ SRR2061818.fastq -o alignment_CP009072_result.sam Welcome to SNAP version 1.0beta.24. Loading index from directory... 0s. 5131767 bases, seed size 20 Aligning. Segmentation fault (core dumped)` i dont know why the error happen. could someone help me? CP009072.1.fasta download from here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ebi.ac.uk%2Fena%2Fdata%2Fview%2FCP009072%26display%3Dfasta%26download%3Dfasta%26filename%3DCP009072.fasta&data=02%7C01%7Cbolosky%40microsoft.com%7C1380e8bb50964d32ca7c08d756e32b1d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637073405986340899&sdata=Q8fXrXXYhk6ILxyOHJ3zgpRA73BbMzQZdpGonZhAKX0%3D&reserved=0> SRR2061818.fastq download from here — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famplab%2Fsnap%2Fissues%2F123%3Femail_source%3Dnotifications%26email_token%3DAAHPTWJHPNZQGWJ6ZDNFF3LQP3P3LA5CNFSM4JDOJ2N2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HTPBJJQ&data=02%7C01%7Cbolosky%40microsoft.com%7C1380e8bb50964d32ca7c08d756e32b1d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637073405986350903&sdata=cNFV3MMc37sX2unUg5ZwDAD6RgkX%2B7oPtQ4aXD5eV2c%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHPTWKGIP3W5SJIX6WVPSDQP3P3LANCNFSM4JDOJ2NQ&data=02%7C01%7Cbolosky%40microsoft.com%7C1380e8bb50964d32ca7c08d756e32b1d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637073405986350903&sdata=a5XwGv3lAFDx5TuOSmPjcu6eFSo8tfRKeyFqi7IqDCw%3D&reserved=0>.

SRR2061818,fastq link is here: ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR206/008/SRR2061818/SRR2061818.fastq.gz

**Comment by bolosky** [comment]
I ran it and it seemed to work fine.

What OS and version are you using?  How much memory (not that you need much for such a small reference)?

I ran on Ubuntu 18.04.  I did a clean install of everything, built snap from github and ran it with your input files and command lines, and it just worked.  I also ran it on Windows, and that was fine, too.

--Bill

**Comment by sjlgg** [comment]
i run it on ubuntu 18.04. 32 GB RAM. I also install it from github and just build it.

Is that the 32GB memory too little to run it?

**Comment by bolosky** [comment]
32GB should be more than enough, especially with the small reference you’re using.

Maybe you can run it under gdb and send me the stack trace when it crashes.

Do this:

sudo apt-get install gdb
cd <your SNAP build directory>
make clean
make CXXFLAGS="-g -O0 -std=c++98 -Wno-format -MMD -ISNAPLib -msse"
gdb ./snap-aligner
run single CP009072_index/ SRR2061818.fastq -o alignment_CP009072_result.sam

(You might have to include the full pathnames of the index and input files on the run line, depending on where they are.)

Then when it fails, run “bt” and send me the output.

--Bill

**Comment by sjlgg** [comment]
Hello bolosky. I have something to do and come back to this problem now. After remake as you say above. It could run successfully. I think it must be my fault. Maybe i make some error in last compile. Thank you for your help.

And the result of my test this time is shown as below, it's run without problem.
`gdb snap-aligner
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from snap-aligner...done.
(gdb) run single CP009072_index/ SRR2061818.fastq -o alignment_CP009072_result.sam
Starting program: /home/sjl/softwares/snap/snap-aligner single CP009072_index/ SRR2061818.fastq -o alignment_CP009072_result.sam
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Welcome to SNAP version 1.0beta.24.

Loading index from directory... 0s.  5131767 bases, seed size 20
Aligning.
[New Thread 0x7ffff7f1f740 (LWP 5209)]
[New Thread 0x7fffef039700 (LWP 5211)]
[Thread 0x7fffef039700 (LWP 5211) exited]
[New Thread 0x7fffef039700 (LWP 5212)]
[Thread 0x7fffef039700 (LWP 5212) exited]
[New Thread 0x7fffef039700 (LWP 5213)]
[New Thread 0x7fffee0ce700 (LWP 5214)]
[New Thread 0x7fff61fc8700 (LWP 5215)]
[New Thread 0x7fff61183700 (LWP 5216)]
[New Thread 0x7fff1ca35700 (LWP 5217)]
[New Thread 0x7ffe94a35700 (LWP 5218)]
[New Thread 0x7ffe52add700 (LWP 5219)]
[New Thread 0x7ffe522dc700 (LWP 5220)]
[Thread 0x7ffe52add700 (LWP 5219) exited]
[Thread 0x7ffe522dc700 (LWP 5220) exited]
[New Thread 0x7ffe522dc700 (LWP 5221)]
[Thread 0x7ffe522dc700 (LWP 5221) exited]
[New Thread 0x7ffe522dc700 (LWP 5222)]
[Thread 0x7ffe522dc700 (LWP 5222) exited]
[New Thread 0x7ffe522dc700 (LWP 5223)]
[New Thread 0x7ffe52add700 (LWP 5224)]
[Thread 0x7ffe522dc700 (LWP 5223) exited]
[Thread 0x7ffe52add700 (LWP 5224) exited]
[New Thread 0x7ffe52add700 (LWP 5225)]
[New Thread 0x7ffe522dc700 (LWP 5226)]
[Thread 0x7ffe52add700 (LWP 5225) exited]
[Thread 0x7ffe522dc700 (LWP 5226) exited]
[New Thread 0x7ffe522dc700 (LWP 5227)]
[Thread 0x7ffe522dc700 (LWP 5227) exited]
[New Thread 0x7ffe522dc700 (LWP 5228)]
[Thread 0x7ffe522dc700 (LWP 5228) exited]
[New Thread 0x7ffe522dc700 (LWP 5229)]
[Thread 0x7ffe522dc700 (LWP 5229) exited]
[New Thread 0x7ffe522dc700 (LWP 5230)]
[Thread 0x7ffe522dc700 (LWP 5230) exited]
[New Thread 0x7ffe522dc700 (LWP 5231)]
[New Thread 0x7ffe52add700 (LWP 5232)]
[Thread 0x7ffe522dc700 (LWP 5231) exited]
[Thread 0x7ffe52add700 (LWP 5232) exited]
[New Thread 0x7ffe52add700 (LWP 5233)]
[Thread 0x7ffe52add700 (LWP 5233) exited]
[New Thread 0x7ffe52add700 (LWP 5234)]
[Thread 0x7ffe52add700 (LWP 5234) exited]
[New Thread 0x7ffe52add700 (LWP 5235)]
[Thread 0x7ffe52add700 (LWP 5235) exited]
[New Thread 0x7ffe52add700 (LWP 5236)]
[Thread 0x7fffee0ce700 (LWP 5214) exited]
[Thread 0x7ffe52add700 (LWP 5236) exited]
[New Thread 0x7ffe52add700 (LWP 5237)]
[Thread 0x7ffe52add700 (LWP 5237) exited]
[Thread 0x7fffef039700 (LWP 5213) exited]
[New Thread 0x7ffe52add700 (LWP 5238)]
[Thread 0x7ffe52add700 (LWP 5238) exited]
[Thread 0x7fff61fc8700 (LWP 5215) exited]
[New Thread 0x7ffe52add700 (LWP 5239)]
[Thread 0x7ffe52add700 (LWP 5239) exited]
[New Thread 0x7ffe52add700 (LWP 5240)]
[Thread 0x7ffe52add700 (LWP 5240) exited]
[Thread 0x7fff61183700 (LWP 5216) exited]
[New Thread 0x7ffe52add700 (LWP 5241)]
[Thread 0x7ffe52add700 (LWP 5241) exited]
[Thread 0x7ffe94a35700 (LWP 5218) exited]
[New Thread 0x7ffe52add700 (LWP 5242)]
[Thread 0x7ffe52add700 (LWP 5242) exited]
Total Reads    Aligned, MAPQ >= 10    Aligned, MAPQ < 10     Unaligned              Too Short/Too Many Ns     Reads/s   Time in Aligner (s)
1,137,984      1,039,490 (91.34%)     31,191 (2.74%)         67,275 (5.91%)         28 (0.00%)                742,324   2
[Thread 0x7fff1ca35700 (LWP 5217) exited]
[Thread 0x7ffff7fd8740 (LWP 5205) exited]
[Inferior 1 (process 5205) exited normally]
(gdb) bt
No stack.
`
