### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Ckhyriem** [amplab/snap#124]
Got the following error when make command was used. Please help.

g++ -O3 -Wno-format -MMD -ISNAPLib -msse   -c -o SNAPLib/AlignerContext.o SNAPLib/AlignerContext.cpp
In file included from /usr/include/c++/6/bits/stl_map.h:63:0,
                 from /usr/include/c++/6/map:61,
                 from SNAPLib/Util.h:3,
                 from SNAPLib/VariableSizeVector.h:3,
                 from SNAPLib/VariableSizeMap.h:5,
                 from SNAPLib/DataReader.h:26,
                 from SNAPLib/Read.h:30,
                 from SNAPLib/AlignerOptions.h:30,
                 from SNAPLib/AlignerContext.cpp:29:
/usr/include/c++/6/tuple:851:29: error: expected primary-expression before ‘.’ token
       noexcept(noexcept(__in._M_swap(__in)))
                             ^
/usr/include/c++/6/tuple: In constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(const std::tuple<_Args1 ...>&)’:
/usr/include/c++/6/tuple:671:76: error: expected primary-expression before ‘)’ token
         : _Inherited(static_cast<const _Tuple_impl<0, _UElements...>&>(__in))
                                                                            ^
/usr/include/c++/6/tuple: In constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(const std::tuple<_Args1 ...>&)’:
/usr/include/c++/6/tuple:683:76: error: expected primary-expression before ‘)’ token
         : _Inherited(static_cast<const _Tuple_impl<0, _UElements...>&>(__in))
                                                                            ^
/usr/include/c++/6/tuple: In constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(std::tuple<_Args1 ...>&&)’:
/usr/include/c++/6/tuple:695:71: error: expected primary-expression before ‘)’ token
         : _Inherited(static_cast<_Tuple_impl<0, _UElements...>&&>(__in)) { }
                                                                       ^
/usr/include/c++/6/tuple: In constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(std::tuple<_Args1 ...>&&)’:
/usr/include/c++/6/tuple:706:71: error: expected primary-expression before ‘)’ token
         : _Inherited(static_cast<_Tuple_impl<0, _UElements...>&&>(__in)) { }
                                                                       ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, const std::tuple< <template-parameter-1-1> >&)’:
/usr/include/c++/6/tuple:760:62: error: expected primary-expression before ‘)’ token
  : _Inherited(__tag, __a, static_cast<const _Inherited&>(__in)) { }
                                                              ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, std::tuple< <template-parameter-1-1> >&&)’:
/usr/include/c++/6/tuple:764:57: error: expected primary-expression before ‘)’ token
  : _Inherited(__tag, __a, static_cast<_Inherited&&>(__in)) { }
                                                         ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, const std::tuple<_Args2 ...>&)’:
/usr/include/c++/6/tuple:775:69: error: expected primary-expression before ‘)’ token
               static_cast<const _Tuple_impl<0, _UElements...>&>(__in))
                                                                     ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, const std::tuple<_Args2 ...>&)’:
/usr/include/c++/6/tuple:787:69: error: expected primary-expression before ‘)’ token
               static_cast<const _Tuple_impl<0, _UElements...>&>(__in))
                                                                     ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, std::tuple<_Args2 ...>&&)’:
/usr/include/c++/6/tuple:799:64: error: expected primary-expression before ‘)’ token
               static_cast<_Tuple_impl<0, _UElements...>&&>(__in))
                                                                ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, std::tuple<_Args2 ...>&&)’:
/usr/include/c++/6/tuple:811:64: error: expected primary-expression before ‘)’ token
               static_cast<_Tuple_impl<0, _UElements...>&&>(__in))
                                                                ^
/usr/include/c++/6/tuple: In member function ‘std::tuple< <template-parameter-1-1> >& std::tuple< <template-parameter-1-1> >::operator=(const std::tuple< <template-parameter-1-1> >&)’:
/usr/include/c++/6/tuple:817:40: error: expected primary-expression before ‘;’ token
  static_cast<_Inherited&>(*this) = __in;
                                        ^
/usr/include/c++/6/tuple: In member function ‘std::tuple< <template-parameter-1-1> >& std::tuple< <template-parameter-1-1> >::operator=(std::tuple< <template-parameter-1-1> >&&)’:
/usr/include/c++/6/tuple:825:50: error: no matching function for call to ‘move()’
  static_cast<_Inherited&>(*this) = std::move(__in);
                                                  ^
In file included from /usr/include/c++/6/bits/stl_pair.h:59:0,
                 from /usr/include/c++/6/utility:70,
                 from /usr/include/c++/6/algorithm:60,
                 from SNAPLib/stdafx.h:13,
                 from SNAPLib/AlignerContext.cpp:26:
/usr/include/c++/6/bits/move.h:101:5: note: candidate: template<class _Tp> constexpr typename std::remove_reference< <template-parameter-1-1> >::type&& std::move(_Tp&&)
     move(_Tp&& __t) noexcept
     ^~~~
/usr/include/c++/6/bits/move.h:101:5: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/6/bits/stl_map.h:63:0,
                 from /usr/include/c++/6/map:61,
                 from SNAPLib/Util.h:3,
                 from SNAPLib/VariableSizeVector.h:3,
                 from SNAPLib/VariableSizeMap.h:5,
                 from SNAPLib/DataReader.h:26,
                 from SNAPLib/Read.h:30,
                 from SNAPLib/AlignerOptions.h:30,
                 from SNAPLib/AlignerContext.cpp:29:
/usr/include/c++/6/tuple:825:50: note:   candidate expects 1 argument, 0 provided
  static_cast<_Inherited&>(*this) = std::move(__in);
                                                  ^
In file included from /usr/include/c++/6/algorithm:61:0,
                 from SNAPLib/stdafx.h:13,
                 from SNAPLib/AlignerContext.cpp:26:
/usr/include/c++/6/bits/stl_algobase.h:479:5: note: candidate: template<class _II, class _OI> _OI std::move(_II, _II, _OI)
     move(_II __first, _II __last, _OI __result)
     ^~~~
/usr/include/c++/6/bits/stl_algobase.h:479:5: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/6/bits/stl_map.h:63:0,
                 from /usr/include/c++/6/map:61,
                 from SNAPLib/Util.h:3,
                 from SNAPLib/VariableSizeVector.h:3,
                 from SNAPLib/VariableSizeMap.h:5,
                 from SNAPLib/DataReader.h:26,
                 from SNAPLib/Read.h:30,
                 from SNAPLib/AlignerOptions.h:30,
                 from SNAPLib/AlignerContext.cpp:29:
/usr/include/c++/6/tuple:825:50: note:   candidate expects 3 arguments, 0 provided
  static_cast<_Inherited&>(*this) = std::move(__in);
                                                  ^
/usr/include/c++/6/tuple: In member function ‘std::tuple< <template-parameter-1-1> >& std::tuple< <template-parameter-1-1> >::operator=(const std::tuple<_Args1 ...>&)’:
/usr/include/c++/6/tuple:835:42: error: expected primary-expression before ‘;’ token
    static_cast<_Inherited&>(*this) = __in;
                                          ^
/usr/include/c++/6/tuple: In member function ‘std::tuple< <template-parameter-1-1> >& std::tuple< <template-parameter-1-1> >::operator=(std::tuple<_Args1 ...>&&)’:
/usr/include/c++/6/tuple:845:52: error: no matching function for call to ‘move()’
    static_cast<_Inherited&>(*this) = std::move(__in);
                                                    ^
In file included from /usr/include/c++/6/bits/stl_pair.h:59:0,
                 from /usr/include/c++/6/utility:70,
                 from /usr/include/c++/6/algorithm:60,
                 from SNAPLib/stdafx.h:13,
                 from SNAPLib/AlignerContext.cpp:26:
/usr/include/c++/6/bits/move.h:101:5: note: candidate: template<class _Tp> constexpr typename std::remove_reference< <template-parameter-1-1> >::type&& std::move(_Tp&&)
     move(_Tp&& __t) noexcept
     ^~~~
/usr/include/c++/6/bits/move.h:101:5: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/6/bits/stl_map.h:63:0,
                 from /usr/include/c++/6/map:61,
                 from SNAPLib/Util.h:3,
                 from SNAPLib/VariableSizeVector.h:3,
                 from SNAPLib/VariableSizeMap.h:5,
                 from SNAPLib/DataReader.h:26,
                 from SNAPLib/Read.h:30,
                 from SNAPLib/AlignerOptions.h:30,
                 from SNAPLib/AlignerContext.cpp:29:
/usr/include/c++/6/tuple:845:52: note:   candidate expects 1 argument, 0 provided
    static_cast<_Inherited&>(*this) = std::move(__in);
                                                    ^
In file included from /usr/include/c++/6/algorithm:61:0,
                 from SNAPLib/stdafx.h:13,
                 from SNAPLib/AlignerContext.cpp:26:
/usr/include/c++/6/bits/stl_algobase.h:479:5: note: candidate: template<class _II, class _OI> _OI std::move(_II, _II, _OI)
     move(_II __first, _II __last, _OI __result)
     ^~~~
/usr/include/c++/6/bits/stl_algobase.h:479:5: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/6/bits/stl_map.h:63:0,
                 from /usr/include/c++/6/map:61,
                 from SNAPLib/Util.h:3,
                 from SNAPLib/VariableSizeVector.h:3,
                 from SNAPLib/VariableSizeMap.h:5,
                 from SNAPLib/DataReader.h:26,
                 from SNAPLib/Read.h:30,
                 from SNAPLib/AlignerOptions.h:30,
                 from SNAPLib/AlignerContext.cpp:29:
/usr/include/c++/6/tuple:845:52: note:   candidate expects 3 arguments, 0 provided
    static_cast<_Inherited&>(*this) = std::move(__in);
                                                    ^
/usr/include/c++/6/tuple: At global scope:
/usr/include/c++/6/tuple:1218:29: error: expected primary-expression before ‘.’ token
       noexcept(noexcept(__in._M_swap(__in)))
                             ^
/usr/include/c++/6/tuple: In constructor ‘constexpr std::tuple<_T1, _T2>::tuple(const std::tuple<_U1, _U2>&)’:
/usr/include/c++/6/tuple:955:64: error: expected primary-expression before ‘)’ token
  : _Inherited(static_cast<const _Tuple_impl<0, _U1, _U2>&>(__in)) { }
                                                                ^
/usr/include/c++/6/tuple: In constructor ‘constexpr std::tuple<_T1, _T2>::tuple(const std::tuple<_U1, _U2>&)’:
/usr/include/c++/6/tuple:964:64: error: expected primary-expression before ‘)’ token
  : _Inherited(static_cast<const _Tuple_impl<0, _U1, _U2>&>(__in)) { }
                                                                ^
/usr/include/c++/6/tuple: In constructor ‘constexpr std::tuple<_T1, _T2>::tuple(std::tuple<_U1, _U2>&&)’:
/usr/include/c++/6/tuple:973:59: error: expected primary-expression before ‘)’ token
  : _Inherited(static_cast<_Tuple_impl<0, _U1, _U2>&&>(__in)) { }
                                                           ^
/usr/include/c++/6/tuple: In constructor ‘constexpr std::tuple<_T1, _T2>::tuple(std::tuple<_U1, _U2>&&)’:
/usr/include/c++/6/tuple:982:59: error: expected primary-expression before ‘)’ token
  : _Inherited(static_cast<_Tuple_impl<0, _U1, _U2>&&>(__in)) { }
                                                           ^
/usr/include/c++/6/tuple: In constructor ‘constexpr std::tuple<_T1, _T2>::tuple(const std::pair<_U1, _U2>&)’:
/usr/include/c++/6/tuple:991:19: error: expected primary-expression before ‘.’ token
  : _Inherited(__in.first, __in.second) { }
                   ^
/usr/include/c++/6/tuple:991:31: error: expected primary-expression before ‘.’ token
  : _Inherited(__in.first, __in.second) { }
                               ^
/usr/include/c++/6/tuple: In constructor ‘constexpr std::tuple<_T1, _T2>::tuple(const std::pair<_U1, _U2>&)’:
/usr/include/c++/6/tuple:1000:19: error: expected primary-expression before ‘.’ token
  : _Inherited(__in.first, __in.second) { }
                   ^
/usr/include/c++/6/tuple:1000:31: error: expected primary-expression before ‘.’ token
  : _Inherited(__in.first, __in.second) { }
                               ^
/usr/include/c++/6/tuple: In constructor ‘constexpr std::tuple<_T1, _T2>::tuple(std::pair<_U1, _U2>&&)’:
/usr/include/c++/6/tuple:1009:37: error: expected primary-expression before ‘.’ token
  : _Inherited(std::forward<_U1>(__in.first),
                                     ^
/usr/include/c++/6/tuple:1010:30: error: expected primary-expression before ‘.’ token
        std::forward<_U2>(__in.second)) { }
                              ^
/usr/include/c++/6/tuple: In constructor ‘constexpr std::tuple<_T1, _T2>::tuple(std::pair<_U1, _U2>&&)’:
/usr/include/c++/6/tuple:1019:37: error: expected primary-expression before ‘.’ token
  : _Inherited(std::forward<_U1>(__in.first),
                                     ^
/usr/include/c++/6/tuple:1020:30: error: expected primary-expression before ‘.’ token
        std::forward<_U2>(__in.second)) { }
                              ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple<_T1, _T2>::tuple(std::allocator_arg_t, const _Alloc&, const std::tuple<_T1, _T2>&)’:
/usr/include/c++/6/tuple:1075:62: error: expected primary-expression before ‘)’ token
  : _Inherited(__tag, __a, static_cast<const _Inherited&>(__in)) { }
                                                              ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple<_T1, _T2>::tuple(std::allocator_arg_t, const _Alloc&, std::tuple<_T1, _T2>&&)’:
/usr/include/c++/6/tuple:1079:57: error: expected primary-expression before ‘)’ token
  : _Inherited(__tag, __a, static_cast<_Inherited&&>(__in)) { }
                                                         ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple<_T1, _T2>::tuple(std::allocator_arg_t, const _Alloc&, const std::tuple<_U1, _U2>&)’:
/usr/include/c++/6/tuple:1090:64: error: expected primary-expression before ‘)’ token
               static_cast<const _Tuple_impl<0, _U1, _U2>&>(__in))
                                                                ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple<_T1, _T2>::tuple(std::allocator_arg_t, const _Alloc&, const std::tuple<_U1, _U2>&)’:
/usr/include/c++/6/tuple:1102:64: error: expected primary-expression before ‘)’ token
               static_cast<const _Tuple_impl<0, _U1, _U2>&>(__in))
                                                                ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple<_T1, _T2>::tuple(std::allocator_arg_t, const _Alloc&, std::tuple<_U1, _U2>&&)’:
/usr/include/c++/6/tuple:1112:71: error: expected primary-expression before ‘)’ token
  : _Inherited(__tag, __a, static_cast<_Tuple_impl<0, _U1, _U2>&&>(__in))
                                                                       ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple<_T1, _T2>::tuple(std::allocator_arg_t, const _Alloc&, std::tuple<_U1, _U2>&&)’:
/usr/include/c++/6/tuple:1123:71: error: expected primary-expression before ‘)’ token
  : _Inherited(__tag, __a, static_cast<_Tuple_impl<0, _U1, _U2>&&>(__in))
                                                                       ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple<_T1, _T2>::tuple(std::allocator_arg_t, const _Alloc&, const std::pair<_U1, _U2>&)’:
/usr/include/c++/6/tuple:1134:31: error: expected primary-expression before ‘.’ token
  : _Inherited(__tag, __a, __in.first, __in.second) { }
                               ^
/usr/include/c++/6/tuple:1134:43: error: expected primary-expression before ‘.’ token
  : _Inherited(__tag, __a, __in.first, __in.second) { }
                                           ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple<_T1, _T2>::tuple(std::allocator_arg_t, const _Alloc&, const std::pair<_U1, _U2>&)’:
/usr/include/c++/6/tuple:1144:31: error: expected primary-expression before ‘.’ token
  : _Inherited(__tag, __a, __in.first, __in.second) { }
                               ^
/usr/include/c++/6/tuple:1144:43: error: expected primary-expression before ‘.’ token
  : _Inherited(__tag, __a, __in.first, __in.second) { }
                                           ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple<_T1, _T2>::tuple(std::allocator_arg_t, const _Alloc&, std::pair<_U1, _U2>&&)’:
/usr/include/c++/6/tuple:1153:49: error: expected primary-expression before ‘.’ token
  : _Inherited(__tag, __a, std::forward<_U1>(__in.first),
                                                 ^
/usr/include/c++/6/tuple:1154:30: error: expected primary-expression before ‘.’ token
        std::forward<_U2>(__in.second)) { }
                              ^
/usr/include/c++/6/tuple: In constructor ‘std::tuple<_T1, _T2>::tuple(std::allocator_arg_t, const _Alloc&, std::pair<_U1, _U2>&&)’:
/usr/include/c++/6/tuple:1164:49: error: expected primary-expression before ‘.’ token
  : _Inherited(__tag, __a, std::forward<_U1>(__in.first),
                                                 ^
/usr/include/c++/6/tuple:1165:30: error: expected primary-expression before ‘.’ token
        std::forward<_U2>(__in.second)) { }
                              ^
/usr/include/c++/6/tuple: In member function ‘std::tuple<_T1, _T2>& std::tuple<_T1, _T2>::operator=(const std::tuple<_T1, _T2>&)’:
/usr/include/c++/6/tuple:1170:40: error: expected primary-expression before ‘;’ token
  static_cast<_Inherited&>(*this) = __in;
                                        ^
/usr/include/c++/6/tuple: In member function ‘std::tuple<_T1, _T2>& std::tuple<_T1, _T2>::operator=(std::tuple<_T1, _T2>&&)’:
/usr/include/c++/6/tuple:1178:50: error: no matching function for call to ‘move()’
  static_cast<_Inherited&>(*this) = std::move(__in);
                                                  ^
In file included from /usr/include/c++/6/bits/stl_pair.h:59:0,
                 from /usr/include/c++/6/utility:70,
                 from /usr/include/c++/6/algorithm:60,
                 from SNAPLib/stdafx.h:13,
                 from SNAPLib/AlignerContext.cpp:26:
/usr/include/c++/6/bits/move.h:101:5: note: candidate: template<class _Tp> constexpr typename std::remove_reference< <template-parameter-1-1> >::type&& std::move(_Tp&&)
     move(_Tp&& __t) noexcept
     ^~~~
/usr/include/c++/6/bits/move.h:101:5: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/6/bits/stl_map.h:63:0,
                 from /usr/include/c++/6/map:61,
                 from SNAPLib/Util.h:3,
                 from SNAPLib/VariableSizeVector.h:3,
                 from SNAPLib/VariableSizeMap.h:5,
                 from SNAPLib/DataReader.h:26,
                 from SNAPLib/Read.h:30,
                 from SNAPLib/AlignerOptions.h:30,
                 from SNAPLib/AlignerContext.cpp:29:
/usr/include/c++/6/tuple:1178:50: note:   candidate expects 1 argument, 0 provided
  static_cast<_Inherited&>(*this) = std::move(__in);
                                                  ^
In file included from /usr/include/c++/6/algorithm:61:0,
                 from SNAPLib/stdafx.h:13,
                 from SNAPLib/AlignerContext.cpp:26:
/usr/include/c++/6/bits/stl_algobase.h:479:5: note: candidate: template<class _II, class _OI> _OI std::move(_II, _II, _OI)
     move(_II __first, _II __last, _OI __result)
     ^~~~
/usr/include/c++/6/bits/stl_algobase.h:479:5: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/6/bits/stl_map.h:63:0,
                 from /usr/include/c++/6/map:61,
                 from SNAPLib/Util.h:3,
                 from SNAPLib/VariableSizeVector.h:3,
                 from SNAPLib/VariableSizeMap.h:5,
                 from SNAPLib/DataReader.h:26,
                 from SNAPLib/Read.h:30,
                 from SNAPLib/AlignerOptions.h:30,
                 from SNAPLib/AlignerContext.cpp:29:
/usr/include/c++/6/tuple:1178:50: note:   candidate expects 3 arguments, 0 provided
  static_cast<_Inherited&>(*this) = std::move(__in);
                                                  ^
/usr/include/c++/6/tuple: In member function ‘std::tuple<_T1, _T2>& std::tuple<_T1, _T2>::operator=(const std::tuple<_U1, _U2>&)’:
/usr/include/c++/6/tuple:1186:42: error: expected primary-expression before ‘;’ token
    static_cast<_Inherited&>(*this) = __in;
                                          ^
/usr/include/c++/6/tuple: In member function ‘std::tuple<_T1, _T2>& std::tuple<_T1, _T2>::operator=(std::tuple<_U1, _U2>&&)’:
/usr/include/c++/6/tuple:1194:52: error: no matching function for call to ‘move()’
    static_cast<_Inherited&>(*this) = std::move(__in);
                                                    ^
In file included from /usr/include/c++/6/bits/stl_pair.h:59:0,
                 from /usr/include/c++/6/utility:70,
                 from /usr/include/c++/6/algorithm:60,
                 from SNAPLib/stdafx.h:13,
                 from SNAPLib/AlignerContext.cpp:26:
/usr/include/c++/6/bits/move.h:101:5: note: candidate: template<class _Tp> constexpr typename std::remove_reference< <template-parameter-1-1> >::type&& std::move(_Tp&&)
     move(_Tp&& __t) noexcept
     ^~~~
/usr/include/c++/6/bits/move.h:101:5: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/6/bits/stl_map.h:63:0,
                 from /usr/include/c++/6/map:61,
                 from SNAPLib/Util.h:3,
                 from SNAPLib/VariableSizeVector.h:3,
                 from SNAPLib/VariableSizeMap.h:5,
                 from SNAPLib/DataReader.h:26,
                 from SNAPLib/Read.h:30,
                 from SNAPLib/AlignerOptions.h:30,
                 from SNAPLib/AlignerContext.cpp:29:
/usr/include/c++/6/tuple:1194:52: note:   candidate expects 1 argument, 0 provided
    static_cast<_Inherited&>(*this) = std::move(__in);
                                                    ^
In file included from /usr/include/c++/6/algorithm:61:0,
                 from SNAPLib/stdafx.h:13,
                 from SNAPLib/AlignerContext.cpp:26:
/usr/include/c++/6/bits/stl_algobase.h:479:5: note: candidate: template<class _II, class _OI> _OI std::move(_II, _II, _OI)
     move(_II __first, _II __last, _OI __result)
     ^~~~
/usr/include/c++/6/bits/stl_algobase.h:479:5: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/6/bits/stl_map.h:63:0,
                 from /usr/include/c++/6/map:61,
                 from SNAPLib/Util.h:3,
                 from SNAPLib/VariableSizeVector.h:3,
                 from SNAPLib/VariableSizeMap.h:5,
                 from SNAPLib/DataReader.h:26,
                 from SNAPLib/Read.h:30,
                 from SNAPLib/AlignerOptions.h:30,
                 from SNAPLib/AlignerContext.cpp:29:
/usr/include/c++/6/tuple:1194:52: note:   candidate expects 3 arguments, 0 provided
    static_cast<_Inherited&>(*this) = std::move(__in);
                                                    ^
/usr/include/c++/6/tuple: In member function ‘std::tuple<_T1, _T2>& std::tuple<_T1, _T2>::operator=(const std::pair<_U1, _U2>&)’:
/usr/include/c++/6/tuple:1202:31: error: expected primary-expression before ‘.’ token
    this->_M_head(*this) = __in.first;
                               ^
/usr/include/c++/6/tuple:1203:46: error: expected primary-expression before ‘.’ token
    this->_M_tail(*this)._M_head(*this) = __in.second;
                                              ^
/usr/include/c++/6/tuple: In member function ‘std::tuple<_T1, _T2>& std::tuple<_T1, _T2>::operator=(std::pair<_U1, _U2>&&)’:
/usr/include/c++/6/tuple:1211:49: error: expected primary-expression before ‘.’ token
    this->_M_head(*this) = std::forward<_U1>(__in.first);
                                                 ^
/usr/include/c++/6/tuple:1212:64: error: expected primary-expression before ‘.’ token
    this->_M_tail(*this)._M_head(*this) = std::forward<_U2>(__in.second);
                                                                ^
<builtin>: recipe for target 'SNAPLib/AlignerContext.o' failed
make: *** [SNAPLib/AlignerContext.o] Error 1

**Comment by bolosky** [comment]
Those are all errors in the system include files, not SNAP proper.  I’m  not sure why you’re getting them specifically, but it’s probably due to having installed a weird version of g++ or something,

Sorry I can’t be more helpful about your specific problem.

**Comment by Ckhyriem** [comment]
Dear Bill,

Thanks for the reply. I will see if other versions of gcc will work with it.

Regards

Costerwell Khyriem
