### ISSUE TITLE
CPU affinity

### ISSUE THREAD

**Issue by jkbonfield** [amplab/snap#137]
Snap-aligner uses `sched_setaffinity` with the processor number coming from threadNum.  This means for N threads it uses CPU 0 to N-1.  At the very least this behaviour would be good to document.

Unfortunately if I run "taskset -c 30,37 snap-aligner -t8" that means it'll (by default) still end up on CPUs 0 to 7.  This has had me chasing my tail all afternoon as to why the speed is so variable (on a shared host with batch scheduling allocating CPUs).

I am aware that `--b` can disable this feature, but it's on by default.  Could it call `sched_getaffinity` first and if not a default mask of all CPUs, disable this feature and honour the environment instead?

**Comment by bolosky** [comment]
Fixed in 2.0.
