### ISSUE TITLE
Binary for Linux

### ISSUE THREAD

**Issue by ksahlin** [amplab/snap#139]
Hi,

I wanted to try the new snap v2.0. The binary for OSx works, but when downloading and running the binary for Linux (snap-aligner) from [here](https://github.com/amplab/snap/releases/tag/v2.0.0) it gives me

```
$ ./snap-aligner 
./snap-aligner: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./snap-aligner)
```

I'm on a server:
```
$ uname -a
Linux rackham3.uppmax.uu.se 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Any ideas?

Best,
Kristoffer

**Comment by slw287r** [comment]
Have a go of this static build [snap-aligner 2.0 static build](https://www.123pan.com/s/skzA-rPXph)

**Comment by bolosky** [comment]
I updated the binary in the github release and on the project webpage to be statically linked.

**Comment by ksahlin** [comment]
Thanks both, it works now.
