### ISSUE TITLE
Is SNAP effective for high error rate  long read data such as Nanopore or others?

### ISSUE THREAD

**Issue by jsonProgram** [amplab/snap#150]
hi Bolosky,
  I want to use SNAP to process nanopore data, I don't know if you have tested it?

Best,
Json

**Comment by bolosky** [comment]
You can uncomment the definition of LONG_READS in Read.h and rebuild.  You'll want to run it with parameters that let it search farther from the read (i.e,. higher values of -d).

That said, it's not designed or tested for nanopore reads, so you might not get the results you want.  I recently tried it on some and it was at least OK at first blush, but that's not the same thing as really testing it.

From: jsonProgram ***@***.***>
Sent: Tuesday, January 18, 2022 12:45 AM
To: amplab/snap ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [amplab/snap] Is SNAP effective for high error rate long read data such as Nanopore or others? (Issue #150)


hi Bolosky,
I want to use SNAP to process nanopore data, I don't know if you have tested it?

Best,
Json

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famplab%2Fsnap%2Fissues%2F150&data=04%7C01%7Cbolosky%40microsoft.com%7C361aaa3793734ec2afb608d9da5ed52d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637780923102731101%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SUn%2BetyYsOrFjC4irTJ73TY566xBAyRRdUe3YRzdZp8%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHPTWM4X5LKB6TVVLY6C23UWUSBJANCNFSM5MGRRA5Q&data=04%7C01%7Cbolosky%40microsoft.com%7C361aaa3793734ec2afb608d9da5ed52d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637780923102731101%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3tEGfJ76xaQoUgTGuVQ7rpWAT7miG%2FhVRS%2F8an1niJ8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbolosky%40microsoft.com%7C361aaa3793734ec2afb608d9da5ed52d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637780923102731101%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2MxR%2BuMxyfy6qsHPRJDRiealxxHVaxX587eHAVyHNdE%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cbolosky%40microsoft.com%7C361aaa3793734ec2afb608d9da5ed52d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637780923102731101%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1NkwUcSdfYOfX3O1TfRPYGyyKdaPidmNf%2BwJwe%2FaEmo%3D&reserved=0>.

**Comment by jsonProgram** [comment]
This information is very helpful for me, thank you!
