### ISSUE TITLE
Settings wrt datatype?

### ISSUE THREAD

**Issue by matthdsm** [amplab/snap#155]
Hi

Are there any recommend settings for different datatypes?
e.g. Shallow WGS for CNV calling, SNP calling voor WES/WGS, ...

Thanks
M

**Comment by arun-sub** [comment]
Thanks for your question. The default SNAP settings should work well for both CNV and SNP calling with GATK's Haplotype Caller as far as I know. Let us know if you run into any issues.

If you are using SNAP with the DRAGEN variant caller, we have the -hc- option to enable some optimizations specific to the DRAGEN variant caller (e.g., better handling of poor alignments with large soft clips, using base quality scores to better identify small INDELs).

**Comment by matthdsm** [comment]
Thank you for the reply!
We're very impressed by the speed of the aligner.  

Does the -hc- option also apply to the open source gatk in dragen mode or is it just for the fpga accelerated cloud version?

**Comment by matthdsm** [comment]
I can't find any docs on `-ht-` in the help or in the manual. Can I find documentation elsewhere?

**Comment by arun-sub** [comment]
-hc- should also apply to the open-source DRAGEN-GATK release

Documentation for -hc- is available in our [user manual](https://github.com/amplab/snap/blob/master/docs/SNAP%20User%20Manual.pdf) under Section "DRAGEN variant caller mode"

We also should have had it as part of the help message, but our help message inadvertently got too long that it overflows the space we allocated for it. We will fix this. Thanks for pointing this out.

**Comment by matthdsm** [comment]
Thanks for the replies! I'm going to close this now
