### ISSUE TITLE
"snap" binary in Quick Start guide

### ISSUE THREAD

**Issue by hubgit** [amplab/snap#156]
In the Quick Start guide, the third example should use command `snap-aligner`, rather than `snap`:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/14294/184838395-d063229f-192e-43bf-b31a-d4513e8fa4da.png">

**Comment by bolosky** [comment]
I fixed it on my machine.  It'll be in my next commit to dev, and then get pushed to master when the rest of the commit looks good.

**Comment by bolosky** [comment]
In 2.0.2
