### ISSUE TITLE
Compression of intermediate bam file

### ISSUE THREAD

**Issue by matthdsm** [amplab/snap#163]
Hi,

Is there an option to compress the intermediate bam file? 
I'm aligning 80GB's worth of fastq files and the intermediate bam's grown to about 500GB, which is becoming quite a load on our FS.

Current command is
```
snap-aligner paired ./snapaligner sample_R1.fastp.fastq.gz sample_R2.fastp.fastq.gz -o sample.bam -t 18 -so -b- -sm 10 -I -hc- 

```

Thanks
M

**Comment by bolosky** [comment]
By "intermediate" BAM file do you mean the sort temporary file that gets created during alignment but before the final output?  The one that's got a name like sample.bam.tmp?

No, there's no option to compress it.  Compressing is really slow and this is the first time that I, at least, have heard that it's been a big problem to find enough space for it so I'd never considered doing it.

If you mean the final output, that is always compressed.  If you're getting a 500GB BAM from 80GB of gzipped FASTQ then something's wrong and we should follow up on it.

--Bill




From: Matthias De Smet ***@***.***>
Sent: Thursday, December 8, 2022 4:00 AM
To: amplab/snap ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [amplab/snap] Compression of intermediate bam file (Issue #163)


Hi,

Is there an option to compress the intermediate bam file?
I'm aligning 80GB's worth of fastq files and the intermediate bam's grown to about 500GB, which is becoming quite a load on our FS.

Current command is

snap-aligner paired ./snapaligner sample_R1.fastp.fastq.gz sample_R2.fastp.fastq.gz -o sample.bam -t 18 -so -b- -sm 10 -I -hc-



Thanks
M

-

**Comment by matthdsm** [comment]
Hi!

The intermediate is the `bam.tmp` file, the final bam is only about 50GB, so thats acceptable.
Anyway, I just wanted to know if it was possible. I prefer speed over size anyways.

Thanks for the reply!
M

**Comment by ghuls** [comment]
I think SAMtools compresses temporary BAM files, but only with compression level 1 (to have some compression, but not to much CPU overhead).
