### ISSUE TITLE
Why SNAP is not distributed naturally and does not support ADAM format directly?

### ISSUE THREAD

**Issue by alartin** [amplab/snap#25]
I just wonder why snap does not use mapreduce of hadoop/spark as the mapping engine and why it does not support ADAM directly.

**Comment by gurvindersingh** [comment]
any update on writing ADAM files directly from SNAP. As this will help in reducing one extra step require to convert SAM/BAM to ADAM later on.

**Comment by bolosky** [comment]
I’m not working on it.  I don’t know how much (if any) progress people on the ADAM side have made.

**Comment by gurvindersingh** [comment]
Ok thanks Bill. 

I have looked at the ADAM project is seems to be using SNAP in their avocado project to align data. It uses SNAPs stdin and stdout functionality. There is one issue though, it seems that SNAP can not read refernece index from HDFS, so it foces the reference index to be located on all the spark worker nodes, which seems bit of overkill. It would be nice if SNAP can read reference genome index from HDFS. It might be there and I am missing it, can you please let me know status about it.

**Comment by bolosky** [comment]
Jeremy Elson did some work to make SNAP read directly from HDFS, so I think it can do it.  I believe all you need to do is to prefix the filename with hdfs:, so you can do:

Snap paired hdfs:/users/Bolosky/indices/hg19-20 hdfs:/users/Bolosky/reads/sample_reads.sam –o hdfs:/users/Bolosky/sample_snap_aligned.bam

I’m pretty sure that you can map files from HDFS, so you’ll wind up reading and copying the entire index, which is somewhat painful.

I haven’t used it, so YMMV.  It may be that the HDFS support only works on Windows, and I do think that it requires SNAP to be compiled with a flag set.

--Bill

**Comment by gurvindersingh** [comment]
I will test it out.. do you know which flag over the top ?
