### ISSUE TITLE
Providing incorrect fasta file to index results in segmentation violation when searching

### ISSUE THREAD

**Issue by bamueh** [amplab/snap#26]
Providing a fasta file without a header to snap index like so:

```
TAAAAAAATTTCTTAAAATAGCTTTAGAAACACCAGTCTGGATCTGTCCCATTAACTACTCCCTCCTAGCCAGCCTACTCCCAAAAGGATACCCCGGCCGGGTGAATGAAATTTTACACATACT
```

does not result in an error when calling

```sh
$ snap index file.fasta .
```

When using the resulting database, a segmentation violation occurs:

```sh
$ snap single . infile.fastq -o outfile.sam
Welcome to SNAP version 1.0beta.10.

Loading index from directory... 0s.  624 bases, seed size 20
MaxHits	MaxDist	%Used	%Unique	%Multi	%!Found	%Error	%Pairs	lvCalls	NumReads	Reads/s
Segmentation fault: 11
```

If you need more information (e.g., the contents of infile.fastq), let me know.

**Comment by bolosky** [comment]
Fixed in 1.0dev.68.  If a FASTA file doesn't start with ">", snap will generate an error instead of building a broken index.
