### ISSUE TITLE
Should be able to index human reference in 64Gb RAM

### ISSUE THREAD

**Issue by rnpandya** [amplab/snap#4]
From Ilya Chorny ichorny@gmail.com

Hi I am getting the

terminate called after throwing an instance of 'std::bad_alloc'
  what():  St9bad_alloc

error message. I do not have root access on my machine so I can't execute sudo sysctl vm.overcommit_memory=. The node has

Mem:  49540928k total,  5868664k used, 43672264k free,     3668k buffers
Swap:  1020116k total,    20432k used,   999684k free,  4374616k cached

Is there another work around to build an index. If not can you share the hg19 index with me?

Thanks,

Ilya
....
Looks like I got it working on a 192GB Linux box, BTW, it failed also on a 72GB windows 2008 machine.

Thanks,

Ilya

**Comment by bolosky** [comment]
It works (barely) in 32GB now, and easily in 64GB.  This has also been true for quite a while.
