### ISSUE TITLE
SNAP name conflicts

### ISSUE THREAD

**Issue by sjackman** [amplab/snap#41]
The SNAP name is already taken by the SNAP (Semi-HMM-based Nucleic Acid Parser) gene prediction tool, [doi:10.1186/1471-2105-5-59](http://dx.doi.org/10.1186/1471-2105-5-59). Conflicting names cause all sorts of trouble and confusion when referring to software and also when installing software. Would you consider renaming the tool? For example

```
❯❯❯ brew install snap-aligner
==> Installing snap-aligner from homebrew/homebrew-science
Error: Cannot install snap-aligner because conflicting formulae are installed.

  snap: because both install bin/snap
```

**Comment by sjackman** [comment]
Any resolution to this issue? It's a tad annoying that the SNAP gene prediction software and SNAP aligner can't be installed at the same time. Would you consider adding a suffix to the bin/snap executable to make the name unique? snap-map, snappier, snap-aligner, ampsnap, anything really.

**Comment by bolosky** [comment]
I'm going to change it to SNAP (all caps) for the Linux build (Windows file names are case insensitive, but I doubt that the other snap works on Windows anyway).  Hopefully that will both preserve the name of the tool and avoid file name conflicts.  SNAP is an awful backronym anyway (Scalable Nucleotide Alignment Program), so all caps kind of makes sense.

**Comment by bolosky** [comment]
I changed the Linux/MAX output binary name to SNAP instead of snap.  Make clean will delete snap, but if you've installed it somewhere, it's up to you to get rid of it.

**Comment by sjackman** [comment]
Mac OS uses a case-insensitive file system.

**Comment by mr-c** [comment]
This is also a problem for Debian where package names are all lowercase and Ian Korf's `snap` is already packaged.

As for humans, I find 'snap' and 'SNAP' easy to confuse conversationally.

**Comment by mr-c** [comment]
Oh, I just saw that the project was renamed on the dev branch. Very glad to hear it. 

https://groups.google.com/d/msg/snap-user/VSJf1wygiog/O8BCmGBPkL0J

**Comment by sjackman** [comment]
The new name is `snap-aligner`.
