### ISSUE TITLE
Seg fault with -om 5

### ISSUE THREAD

**Issue by macmanes** [amplab/snap#42]
I am having a seq fault occurring with use of `-om 5`. I believe this is a dataset reference specific error, as I can use this flag without issue on other datasets. This is with SNAP version 1.0dev.66, and 1.0dev.63 has the same problem. 

> Mapping using default settings. All is well here.

    snap paired new /mouse/feeding/SRR797058.P2_1P.fq /mouse/feeding/SRR797058.P2_2P.fq -o test.bam -t 40
    Welcome to SNAP version 1.0dev.66.

    Loading index from directory... 1s.  314490333 bases, seed size 20
    Total Reads    Aligned, MAPQ >= 10    Aligned, MAPQ < 10     Unaligned              Too Short/Too Many Ns  %Pairs       Reads/s   Time in Aligner (s)
    465,688,842    120,505,116 (25.88%)   183,822,065 (39.47%)   104,160,832 (22.37%)   57,200,829 (12.28%)    38.96%%      578,563   805

>Mapping with -D 5 All is well here.

    snap paired new /mouse/feeding/SRR797058.P2_1P.fq /mouse/feeding/SRR797058.P2_2P.fq -o test.bam -t 40 -D 5
    Welcome to SNAP version 1.0dev.66.

    Loading index from directory... 1s.  314490333 bases, seed size 20
    Total Reads    Aligned, MAPQ >= 10    Aligned, MAPQ < 10     Unaligned              Too Short/Too Many Ns  %Pairs       Reads/s   Time in Aligner (s)
    465,688,842    120,495,355 (25.87%)   183,831,826 (39.48%)   104,160,832 (22.37%)   57,200,829 (12.28%)    38.96%%      569,672   817

>Mapping with -D5 -om 5 **badness**

    snap paired new /mouse/feeding/SRR797058.P2_1P.fq /mouse/feeding/SRR797058.P2_2P.fq -o test.bam -t 40 -D 5 -om 5
    Welcome to SNAP version 1.0dev.66.

    Loading index from directory... 1s.  314490333 bases, seed size 20
    Total Reads    Aligned, MAPQ >= 10    Aligned, MAPQ < 10     Unaligned              Too Short/Too Many Ns  %Pairs       Reads/s   Time in Aligner (s)
    Segmentation fault (core dumped) 

Happy to help troubleshoot and or make the dataset available. 

cc: @Blahah

**Comment by bolosky** [comment]
If you can let me have the dataset, I can probably repro and fix it quickly.

--Bill

**Comment by macmanes** [comment]
Bill, 

The reference assembly is here: https://www.dropbox.com/s/nzlsmxripetptik/100M.ec.P2.C50.score.Trinity_FIXED.fasta.gz

I'm going to try and see if I can create a small read dataset that recapitulates the problem. The full dataset is on the SRA, if that it helpful. SRR797058

**Comment by macmanes** [comment]
Should have just waited to send the previous message, as making a test case was easier than I thought. The read sets are 100Mb, take 14 seconds to run using 8 threads. Probably could have made them smaller, but this seems sufficient. 

    snap index 100M.ec.P2.C50.score.Trinity_FIXED.fasta new

    snap paired new test1.fq.gz test2.fq.gz -o test1.bam -t 8 -D 5 -om 5
    
    Welcome to SNAP version 1.0dev.66.
    Loading index from directory... 1s.  314490333 bases, seed size 20
    Total Reads    Aligned, MAPQ >= 10    Aligned, MAPQ < 10     Unaligned              Too Short/Too Many Ns  %Pairs       Reads/s   Time in Aligner (s)
    Segmentation fault (core dumped)

The reads are here: 
https://www.dropbox.com/s/bp8h0s8at4d864j/test1.fq.gz
https://www.dropbox.com/s/qmyxhy67bavfwla/test2.fq.gz

Run is successful when losing the `-om 5` flag

**Comment by bolosky** [comment]
OK, it should be fixed in 1.0dev.67.

**Comment by macmanes** [comment]
Looks good to me. Thanks for the fast fix!
