### ISSUE TITLE
fix EventTest, single waiter

### ISSUE THREAD

**Issue by Blahah** [amplab/snap#45]
As mentioned [here](https://groups.google.com/forum/#!searchin/snap-user/test/snap-user/t70z5xDQUA4/GlrXYGAaW0wJ), there is an ongoing bug in [EventTest](https://github.com/amplab/snap/blob/dev/tests/EventTest.cpp). This is causing tests to fail for my PRs ;)

**Comment by bolosky** [comment]
That's fixed in dev, next time we reintegrate it'll be in master.

Sent from my Windows Phone
________________________________

**Comment by Blahah** [comment]
that's odd, because my PRs are based on dev HEAD, so surely that test shouldn't be failing in them?

**Comment by bolosky** [comment]
Fixed in 1.0dev.68.  I swear I already did this once, but somehow the code got lost and not checked in.
