### ISSUE TITLE
Switch over dev branch to master

### ISSUE THREAD

**Issue by arahuja** [amplab/snap#49]
We noticed some significant issues in the `master` branch of SNAP that seem resolved in the `dev` branch - seems it would be worth posting something on this or switching the dev branch over to master?

Below are some of the alignments we saw in `master` where reads are somewhat random and do not appear in `dev`
![image](https://cloud.githubusercontent.com/assets/455755/6699130/6cb4fa9c-ccd5-11e4-9ed3-44bf20d92bb9.png)

**Comment by bolosky** [comment]
Done.
