### ISSUE TITLE
-so functionality is different in dev branch

### ISSUE THREAD

**Issue by arahuja** [amplab/snap#50]
Using the `-so` flag on the `dev` branch build does not give properly sorted files.  This may be more of an issue with `samtools` than with SNAP, but when I use `samtools index` on the file output from SNAP with `-so` flag I get the following error:

```
[E::hts_idx_push] unsorted positions
```

On the `master` branch, I was able to index files without sorting again

**Comment by bolosky** [comment]
Ravi fixed this in 1.0dev.72.
