### ISSUE TITLE
Further development?

### ISSUE THREAD

**Issue by sklages** [amplab/snap#77]
I am looking for a bwa-mem alternative for aligning human/mouse WGS/WES data.
Is there any active development of snap going on? Master branch seems quite outdated.
Are there publications available using `snap` as "main read mapper" in their projects?

best,
Sven

**Comment by bolosky** [comment]
Yes, we’re still working on SNAP some.  I had an intern working on extending it to map 10x reads, for instance (though that isn’t done yet).

I’ve got plans to do more work on it to add things like split read mapping and to do things like auto-calibrating the distance between paired-end reads, though I’m not sure when that will be finished.

And yes, it’s probably time to update master to what’s in dev before we go adding more features.

**Comment by sklages** [comment]
OK, thanks for the info.
