### ISSUE TITLE
what is the command looks like for  SNAP paired  to use stdin/stdout

### ISSUE THREAD

**Issue by wangzhenkeep** [amplab/snap#85]
The sinlge command looks like : snap single myIndex -fastq - -o -sam -.
Dose pairend support to use stdin/stdout? And  can you give an example?

Thanks!

**Comment by bolosky** [comment]
The issue with paired reads is that you’ve only got one stdin for two files.

If you have an interleaved FASTQ (read pairs that come one after another, so four lines for the first end then four lines for the second, repeated) then you can do it (BTW, this is not a standard file format, we made it up).  As you can with SAM or BAM input.  Or you could take one end from stdin and one from an input file, although it’s kind of hard to imagine how that would come up.

So:

snap paired myIndex -pairedInterleavedFastq - -o -sam –
snap paired myIndex -pairedFastq – secondEndFile.fq -o -sam –
snap paired myIndex -sam - -o -sam –

I’m not sure what else we can do given the limitations of how input redirection works.

--Bill

**Comment by wangzhenkeep** [comment]
Thanks！！！！   
“snap paired myIndex -sam - -o -sam –” ，I like this command very much.
